{"incident_id": null, "incident_title": "Out of Memory Error detected in data-processor", "incident_service": "data-processor", "incident_severity": "high", "timestamp": "2025-07-30T14:14:55.361231", "overall_success": true, "total_actions": 2, "successful_actions": 2, "failed_actions": 0, "action_attempts": [{"action_id": "42e76167-854d-4ad2-b1fc-f9033d8d5392", "action_type": "restart_service", "parameters": {"service_name": "data-processor"}, "success": true, "execution_time": 0.5289828777313232, "sequence_position": 1, "timestamp": "2025-07-30T14:14:54.124000"}, {"action_id": "3f3f6afb-b143-48a5-8cd6-8d0bf696f7bc", "action_type": "scale_resources", "parameters": {"service_name": "data-processor", "replicas": 2}, "success": true, "execution_time": 1.204481840133667, "sequence_position": 2, "timestamp": "2025-07-30T14:14:55.343762"}]}
